# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 999243873452c6e20065136cd74932a35afe71a41d7ccc8bc9541d521f75a142354a44b6b80573cd40b6169ccfdd98a6e8824cc583e9cd43e922b371606dad4f

test:
  secret_key_base: 741c730eb93a098ff86d07f4bb3332d849660d95d4814eda89da857fbf02d99f3b154881507f88323eef4a6a7619052ddaf12f9fcfc3852aed9e2bb41792ac12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
